### ISSUE TITLE
Gradle caching system no longer working

### ISSUE THREAD

**Issue by carsongee** [pulumi/pulumi-upgrade-provider-action#39]
### What happened?

We're seeing these cache failure issues from the Gradle plugin as of today:
```
Save Gradle distribution 7.6 failed: Error: reserveCache failed: Request timeout:
```

From a google search I landed on https://github.com/orgs/community/discussions/160793 which suggests the gradle plugin probably needs an update as they deprecated the caching mechanism it is using

### Example

Run this action:
```
name: Upgrade provider
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@v0.0.16
```

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
